//
// Created by rainmanp7 on 2/14/18.
//

#ifndef CRYPTONOTE_TRANSACTIONEXTRAMERGEMININGTAG_H
#define CRYPTONOTE_TRANSACTIONEXTRAMERGEMININGTAG_H


class TransactionExtraMergeMiningTag {

};


#endif //CRYPTONOTE_TRANSACTIONEXTRAMERGEMININGTAG_H
